# Generated by Django 6.0 on 2025-12-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('prediction', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('total_samples', models.IntegerField()),
                ('human_samples', models.IntegerField()),
                ('non_human_samples', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historial de Entrenamiento',
                'verbose_name_plural': 'Historiales de Entrenamiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
